// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ssh_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSSHSessionForHost = `-- name: CountActiveSSHSessionForHost :one
SELECT COUNT(*) FROM ssh_sessions
WHERE host_id = $1 AND status IN ('opening', 'active')
`

func (q *Queries) CountActiveSSHSessionForHost(ctx context.Context, hostID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSSHSessionForHost, hostID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveSSHSessionForUser = `-- name: CountActiveSSHSessionForUser :one
SELECT COUNT(*) FROM ssh_sessions
WHERE user_id = $1 AND status IN ('opening', 'active')
`

func (q *Queries) CountActiveSSHSessionForUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSSHSessionForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSSHRecordingAccessAudit = `-- name: CreateSSHRecordingAccessAudit :one
INSERT INTO ssh_recording_access_audit (id, session_id, user_id, action, client_ip)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, session_id, user_id, action, client_ip, created_at
`

type CreateSSHRecordingAccessAuditParams struct {
	ID        string  `json:"id"`
	SessionID string  `json:"session_id"`
	UserID    string  `json:"user_id"`
	Action    string  `json:"action"`
	ClientIp  *string `json:"client_ip"`
}

func (q *Queries) CreateSSHRecordingAccessAudit(ctx context.Context, arg CreateSSHRecordingAccessAuditParams) (SshRecordingAccessAudit, error) {
	row := q.db.QueryRow(ctx, createSSHRecordingAccessAudit,
		arg.ID,
		arg.SessionID,
		arg.UserID,
		arg.Action,
		arg.ClientIp,
	)
	var i SshRecordingAccessAudit
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Action,
		&i.ClientIp,
		&i.CreatedAt,
	)
	return i, err
}

const createSSHSession = `-- name: CreateSSHSession :one
INSERT INTO ssh_sessions (
    id, host_id, user_id, linux_username, transport, status, client_ip,
    user_agent, started_at, recorded
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, CURRENT_TIMESTAMP, $9)
RETURNING id, host_id, user_id, linux_username, transport, status, client_ip, user_agent, started_at, ended_at, duration_ms, failure_reason, recorded, event_count, recording_bytes, recording_deleted_at, created_at
`

type CreateSSHSessionParams struct {
	ID            string  `json:"id"`
	HostID        string  `json:"host_id"`
	UserID        string  `json:"user_id"`
	LinuxUsername string  `json:"linux_username"`
	Transport     string  `json:"transport"`
	Status        string  `json:"status"`
	ClientIp      *string `json:"client_ip"`
	UserAgent     *string `json:"user_agent"`
	Recorded      bool    `json:"recorded"`
}

func (q *Queries) CreateSSHSession(ctx context.Context, arg CreateSSHSessionParams) (SshSession, error) {
	row := q.db.QueryRow(ctx, createSSHSession,
		arg.ID,
		arg.HostID,
		arg.UserID,
		arg.LinuxUsername,
		arg.Transport,
		arg.Status,
		arg.ClientIp,
		arg.UserAgent,
		arg.Recorded,
	)
	var i SshSession
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.UserID,
		&i.LinuxUsername,
		&i.Transport,
		&i.Status,
		&i.ClientIp,
		&i.UserAgent,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationMs,
		&i.FailureReason,
		&i.Recorded,
		&i.EventCount,
		&i.RecordingBytes,
		&i.RecordingDeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSSHHostAccount = `-- name: DeleteSSHHostAccount :exec
DELETE FROM ssh_host_accounts WHERE host_id = $1 AND linux_username = $2
`

type DeleteSSHHostAccountParams struct {
	HostID        string `json:"host_id"`
	LinuxUsername string `json:"linux_username"`
}

func (q *Queries) DeleteSSHHostAccount(ctx context.Context, arg DeleteSSHHostAccountParams) error {
	_, err := q.db.Exec(ctx, deleteSSHHostAccount, arg.HostID, arg.LinuxUsername)
	return err
}

const getSSHHostAccount = `-- name: GetSSHHostAccount :one
SELECT id, host_id, linux_username, allow_sudo, created_at, updated_at FROM ssh_host_accounts WHERE host_id = $1 AND linux_username = $2
`

type GetSSHHostAccountParams struct {
	HostID        string `json:"host_id"`
	LinuxUsername string `json:"linux_username"`
}

func (q *Queries) GetSSHHostAccount(ctx context.Context, arg GetSSHHostAccountParams) (SshHostAccount, error) {
	row := q.db.QueryRow(ctx, getSSHHostAccount, arg.HostID, arg.LinuxUsername)
	var i SshHostAccount
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.LinuxUsername,
		&i.AllowSudo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSSHSession = `-- name: GetSSHSession :one
SELECT id, host_id, user_id, linux_username, transport, status, client_ip, user_agent, started_at, ended_at, duration_ms, failure_reason, recorded, event_count, recording_bytes, recording_deleted_at, created_at FROM ssh_sessions WHERE id = $1
`

func (q *Queries) GetSSHSession(ctx context.Context, id string) (SshSession, error) {
	row := q.db.QueryRow(ctx, getSSHSession, id)
	var i SshSession
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.UserID,
		&i.LinuxUsername,
		&i.Transport,
		&i.Status,
		&i.ClientIp,
		&i.UserAgent,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationMs,
		&i.FailureReason,
		&i.Recorded,
		&i.EventCount,
		&i.RecordingBytes,
		&i.RecordingDeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listExpiredSSHRecordings = `-- name: ListExpiredSSHRecordings :many
SELECT id, host_id, user_id, linux_username, transport, status, client_ip, user_agent, started_at, ended_at, duration_ms, failure_reason, recorded, event_count, recording_bytes, recording_deleted_at, created_at FROM ssh_sessions
WHERE recorded = true
  AND recording_deleted_at IS NULL
  AND started_at < $1
ORDER BY started_at
LIMIT $2
`

type ListExpiredSSHRecordingsParams struct {
	StartedAt pgtype.Timestamp `json:"started_at"`
	Limit     int32            `json:"limit"`
}

func (q *Queries) ListExpiredSSHRecordings(ctx context.Context, arg ListExpiredSSHRecordingsParams) ([]SshSession, error) {
	rows, err := q.db.Query(ctx, listExpiredSSHRecordings, arg.StartedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SshSession
	for rows.Next() {
		var i SshSession
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.UserID,
			&i.LinuxUsername,
			&i.Transport,
			&i.Status,
			&i.ClientIp,
			&i.UserAgent,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationMs,
			&i.FailureReason,
			&i.Recorded,
			&i.EventCount,
			&i.RecordingBytes,
			&i.RecordingDeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSSHHostAccounts = `-- name: ListSSHHostAccounts :many
SELECT id, host_id, linux_username, allow_sudo, created_at, updated_at FROM ssh_host_accounts WHERE host_id = $1 ORDER BY linux_username
`

func (q *Queries) ListSSHHostAccounts(ctx context.Context, hostID string) ([]SshHostAccount, error) {
	rows, err := q.db.Query(ctx, listSSHHostAccounts, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SshHostAccount
	for rows.Next() {
		var i SshHostAccount
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.LinuxUsername,
			&i.AllowSudo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSSHSessionRecordings = `-- name: ListSSHSessionRecordings :many
SELECT s.id, s.host_id, s.user_id, s.linux_username, s.transport, s.status, s.client_ip, s.user_agent, s.started_at, s.ended_at, s.duration_ms, s.failure_reason, s.recorded, s.event_count, s.recording_bytes, s.recording_deleted_at, s.created_at, h.friendly_name AS host_name, u.username AS patchmon_username
FROM ssh_sessions s
JOIN hosts h ON h.id = s.host_id
JOIN users u ON u.id = s.user_id
WHERE s.recorded = true
  AND ($1::text IS NULL OR s.host_id = $1)
  AND ($2::text IS NULL OR s.user_id = $2)
  AND ($3::text IS NULL OR s.linux_username = $3)
  AND ($4::text IS NULL OR s.status = $4)
  AND ($5::timestamp IS NULL OR s.started_at >= $5)
  AND ($6::timestamp IS NULL OR s.started_at <= $6)
ORDER BY s.started_at DESC
LIMIT $8 OFFSET $7
`

type ListSSHSessionRecordingsParams struct {
	HostID        *string          `json:"host_id"`
	UserID        *string          `json:"user_id"`
	LinuxUsername *string          `json:"linux_username"`
	Status        *string          `json:"status"`
	StartedAfter  pgtype.Timestamp `json:"started_after"`
	StartedBefore pgtype.Timestamp `json:"started_before"`
	OffsetCount   int32            `json:"offset_count"`
	LimitCount    int32            `json:"limit_count"`
}

type ListSSHSessionRecordingsRow struct {
	ID                 string           `json:"id"`
	HostID             string           `json:"host_id"`
	UserID             string           `json:"user_id"`
	LinuxUsername      string           `json:"linux_username"`
	Transport          string           `json:"transport"`
	Status             string           `json:"status"`
	ClientIp           *string          `json:"client_ip"`
	UserAgent          *string          `json:"user_agent"`
	StartedAt          pgtype.Timestamp `json:"started_at"`
	EndedAt            pgtype.Timestamp `json:"ended_at"`
	DurationMs         *int64           `json:"duration_ms"`
	FailureReason      *string          `json:"failure_reason"`
	Recorded           bool             `json:"recorded"`
	EventCount         int64            `json:"event_count"`
	RecordingBytes     int64            `json:"recording_bytes"`
	RecordingDeletedAt pgtype.Timestamp `json:"recording_deleted_at"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	HostName           string           `json:"host_name"`
	PatchmonUsername   string           `json:"patchmon_username"`
}

func (q *Queries) ListSSHSessionRecordings(ctx context.Context, arg ListSSHSessionRecordingsParams) ([]ListSSHSessionRecordingsRow, error) {
	rows, err := q.db.Query(ctx, listSSHSessionRecordings,
		arg.HostID,
		arg.UserID,
		arg.LinuxUsername,
		arg.Status,
		arg.StartedAfter,
		arg.StartedBefore,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSSHSessionRecordingsRow
	for rows.Next() {
		var i ListSSHSessionRecordingsRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.UserID,
			&i.LinuxUsername,
			&i.Transport,
			&i.Status,
			&i.ClientIp,
			&i.UserAgent,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationMs,
			&i.FailureReason,
			&i.Recorded,
			&i.EventCount,
			&i.RecordingBytes,
			&i.RecordingDeletedAt,
			&i.CreatedAt,
			&i.HostName,
			&i.PatchmonUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSSHRecordingDeleted = `-- name: MarkSSHRecordingDeleted :exec
UPDATE ssh_sessions
SET recording_deleted_at = CURRENT_TIMESTAMP, recording_bytes = 0
WHERE id = $1
`

func (q *Queries) MarkSSHRecordingDeleted(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markSSHRecordingDeleted, id)
	return err
}

const updateSSHSessionStatus = `-- name: UpdateSSHSessionStatus :one
UPDATE ssh_sessions SET
    status = $2,
    ended_at = CASE WHEN $2 IN ('completed', 'failed', 'disconnected') THEN CURRENT_TIMESTAMP ELSE ended_at END,
    duration_ms = CASE WHEN $2 IN ('completed', 'failed', 'disconnected')
        THEN (EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - started_at)) * 1000)::BIGINT
        ELSE duration_ms END,
    failure_reason = $3,
    event_count = $4,
    recording_bytes = $5
WHERE id = $1
RETURNING id, host_id, user_id, linux_username, transport, status, client_ip, user_agent, started_at, ended_at, duration_ms, failure_reason, recorded, event_count, recording_bytes, recording_deleted_at, created_at
`

type UpdateSSHSessionStatusParams struct {
	ID             string  `json:"id"`
	Status         string  `json:"status"`
	FailureReason  *string `json:"failure_reason"`
	EventCount     int64   `json:"event_count"`
	RecordingBytes int64   `json:"recording_bytes"`
}

func (q *Queries) UpdateSSHSessionStatus(ctx context.Context, arg UpdateSSHSessionStatusParams) (SshSession, error) {
	row := q.db.QueryRow(ctx, updateSSHSessionStatus,
		arg.ID,
		arg.Status,
		arg.FailureReason,
		arg.EventCount,
		arg.RecordingBytes,
	)
	var i SshSession
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.UserID,
		&i.LinuxUsername,
		&i.Transport,
		&i.Status,
		&i.ClientIp,
		&i.UserAgent,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationMs,
		&i.FailureReason,
		&i.Recorded,
		&i.EventCount,
		&i.RecordingBytes,
		&i.RecordingDeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSSHHostAccount = `-- name: UpsertSSHHostAccount :one
INSERT INTO ssh_host_accounts (id, host_id, linux_username, allow_sudo, created_at, updated_at)
VALUES ($1, $2, $3, $4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (host_id, linux_username) DO UPDATE SET
    allow_sudo = EXCLUDED.allow_sudo,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, host_id, linux_username, allow_sudo, created_at, updated_at
`

type UpsertSSHHostAccountParams struct {
	ID            string `json:"id"`
	HostID        string `json:"host_id"`
	LinuxUsername string `json:"linux_username"`
	AllowSudo     bool   `json:"allow_sudo"`
}

func (q *Queries) UpsertSSHHostAccount(ctx context.Context, arg UpsertSSHHostAccountParams) (SshHostAccount, error) {
	row := q.db.QueryRow(ctx, upsertSSHHostAccount,
		arg.ID,
		arg.HostID,
		arg.LinuxUsername,
		arg.AllowSudo,
	)
	var i SshHostAccount
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.LinuxUsername,
		&i.AllowSudo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
